export const aides = [
  {
    id: "sante",
    title: "Assurance maladie",
    who: "Étudiant inscrit dans un établissement français.",
    benefit: "Une partie des soins peut être remboursée une fois l'affiliation acceptée.",
    caution: "Une assurance voyage ou une mutuelle ne remplace pas cette affiliation.",
    href: "https://etudiant-etranger.ameli.fr/",
    label: "Site des étudiants étrangers",
  },
  {
    id: "crous",
    title: "Logement CROUS",
    who: "Étudiant, avec un calendrier qui change chaque année. Les boursiers sont souvent prioritaires.",
    benefit: "Une résidence étudiante donne une adresse et un loyer encadré.",
    caution: "La demande se fait sur les sites du CROUS, pas auprès d'un intermédiaire.",
    href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F31912",
    label: "Demander un logement CROUS",
  },
  {
    id: "visale",
    title: "Garantie Visale",
    who: "Jeune qui remplit les conditions affichées sur visale.fr, souvent avec un visa étudiant.",
    benefit: "Un garant public peut remplacer une caution familiale.",
    caution: "La demande se fait avant de signer le bail.",
    href: "https://www.visale.fr/",
    label: "Visale",
  },
  {
    id: "caf",
    title: "Aide au logement",
    who: "Selon la situation. Depuis juillet 2026, une partie des étudiants hors Union européenne non boursiers n'y a plus droit.",
    benefit: "Si le droit est ouvert, une partie du loyer peut être aidée après le bail.",
    caution: "Ne signe pas un loyer en comptant sur cette aide avant la décision de la CAF.",
    href: "https://www.service-public.gouv.fr/particuliers/actualites/A18981",
    label: "Conditions officielles",
  },
  {
    id: "transport",
    title: "Transport étudiant",
    who: "Selon la ville et l'âge, avec un certificat de scolarité.",
    benefit: "Un tarif réduit pour aller en cours, quand la ville le prévoit.",
    caution: "Le prix de l'année est sur le site du réseau, pas sur une ancienne capture.",
    href: "https://www.sncf-connect.com/",
    label: "SNCF pour les trajets entre villes",
  },
  {
    id: "travail",
    title: "Travail pendant les études",
    who: "Titulaire d'un visa ou d'une carte étudiant. La limite indiquée par Service-Public est de 964 heures par an.",
    benefit: "Un salaire peut aider le quotidien, dans cette limite.",
    caution: "Au-delà, l'employeur doit obtenir une autorisation. Travailler sans titre valable peut affecter le séjour.",
    href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F2713",
    label: "Règle officielle",
  },
  {
    id: "cvec",
    title: "Services liés à la CVEC",
    who: "Étudiant qui a payé ou été exonéré de la contribution de vie étudiante.",
    benefit: "L'attestation débloque l'inscription. Le produit de la CVEC finance des services de campus.",
    caution: "Paie uniquement sur cvec.etudiant.gouv.fr.",
    href: "https://cvec.etudiant.gouv.fr/",
    label: "CVEC",
  },
];
