export type Intent = "preparer" | "arrive" | "logement" | "emploi" | "demarches";

export type Step = {
  id: string;
  title: string;
  phase: "avant" | "apres";
  intents: Intent[];
  summary: string;
  details: string[];
  links: { label: string; href: string; publisher: string }[];
  caution?: string;
};

export const undecidedCity = "pas-encore";
export const undecidedSchool = "Pas encore décidé";

export function acceptedCity(id: string) {
  return id === undecidedCity || cities.some((item) => item.id === id);
}

const campusNote = "Ce pays relève de la procédure Études en France. La plateforme officielle confirme le circuit, les dates et les pièces.";

export const countries = [
  { id: "afrique-du-sud", name: "Afrique du Sud", note: campusNote },
  { id: "algerie", name: "Algérie", note: campusNote },
  { id: "angola", name: "Angola", note: campusNote },
  { id: "arabie-saoudite", name: "Arabie Saoudite", note: campusNote },
  { id: "argentine", name: "Argentine", note: campusNote },
  { id: "armenie", name: "Arménie", note: campusNote },
  { id: "azerbaidjan", name: "Azerbaïdjan", note: campusNote },
  { id: "bahrein", name: "Bahreïn", note: campusNote },
  { id: "benin", name: "Bénin", note: campusNote },
  { id: "birmanie", name: "Birmanie", note: campusNote },
  { id: "bolivie", name: "Bolivie", note: campusNote },
  { id: "bresil", name: "Brésil", note: campusNote },
  { id: "burkina-faso", name: "Burkina Faso", note: campusNote },
  { id: "burundi", name: "Burundi", note: campusNote },
  { id: "cambodge", name: "Cambodge", note: campusNote },
  { id: "cameroun", name: "Cameroun", note: campusNote },
  { id: "canada", name: "Canada", note: campusNote },
  { id: "chili", name: "Chili", note: campusNote },
  { id: "chine", name: "Chine", note: campusNote },
  { id: "colombie", name: "Colombie", note: campusNote },
  { id: "comores", name: "Comores", note: campusNote },
  { id: "congo", name: "Congo", note: campusNote },
  { id: "coree-du-sud", name: "Corée du Sud", note: campusNote },
  { id: "cote-divoire", name: "Côte d'Ivoire", note: campusNote },
  { id: "djibouti", name: "Djibouti", note: campusNote },
  { id: "emirats-arabes-unis", name: "Émirats arabes unis", note: campusNote },
  { id: "egypte", name: "Égypte", note: campusNote },
  { id: "equateur", name: "Équateur", note: campusNote },
  { id: "etats-unis", name: "États-Unis", note: campusNote },
  { id: "ethiopie", name: "Éthiopie", note: campusNote },
  { id: "gabon", name: "Gabon", note: campusNote },
  { id: "georgie", name: "Géorgie", note: campusNote },
  { id: "ghana", name: "Ghana", note: campusNote },
  { id: "guinee", name: "Guinée", note: campusNote },
  { id: "haiti", name: "Haïti", note: campusNote },
  { id: "hong-kong", name: "Hong-Kong", note: campusNote },
  { id: "inde", name: "Inde", note: campusNote },
  { id: "indonesie", name: "Indonésie", note: campusNote },
  { id: "iran", name: "Iran", note: campusNote },
  { id: "israel", name: "Israël", note: campusNote },
  { id: "japon", name: "Japon", note: campusNote },
  { id: "jordanie", name: "Jordanie", note: campusNote },
  { id: "kenya", name: "Kenya", note: campusNote },
  { id: "koweit", name: "Koweït", note: campusNote },
  { id: "liban", name: "Liban", note: campusNote },
  { id: "madagascar", name: "Madagascar", note: campusNote },
  { id: "malaisie", name: "Malaisie", note: campusNote },
  { id: "mali", name: "Mali", note: campusNote },
  { id: "maroc", name: "Maroc", note: campusNote },
  { id: "maurice", name: "Maurice", note: campusNote },
  { id: "mauritanie", name: "Mauritanie", note: campusNote },
  { id: "mexique", name: "Mexique", note: campusNote },
  { id: "nepal", name: "Népal", note: campusNote },
  { id: "niger", name: "Niger", note: campusNote },
  { id: "nigeria", name: "Nigeria", note: campusNote },
  { id: "pakistan", name: "Pakistan", note: campusNote },
  { id: "perou", name: "Pérou", note: campusNote },
  { id: "qatar", name: "Qatar", note: campusNote },
  { id: "republique-centrafricaine", name: "République Centrafricaine", note: campusNote },
  { id: "republique-democratique-du-congo", name: "République démocratique du Congo", note: campusNote },
  { id: "republique-dominicaine", name: "République dominicaine", note: campusNote },
  { id: "royaume-uni", name: "Royaume-Uni", note: campusNote },
  { id: "russie", name: "Russie", note: campusNote },
  { id: "senegal", name: "Sénégal", note: campusNote },
  { id: "singapour", name: "Singapour", note: campusNote },
  { id: "taiwan", name: "Taïwan", note: campusNote },
  { id: "tchad", name: "Tchad", note: campusNote },
  { id: "thailande", name: "Thaïlande", note: campusNote },
  { id: "togo", name: "Togo", note: campusNote },
  { id: "tunisie", name: "Tunisie", note: campusNote },
  { id: "turquie", name: "Turquie", note: campusNote },
  { id: "ukraine", name: "Ukraine", note: campusNote },
  { id: "vietnam", name: "Vietnam", note: campusNote },
  { id: "autre", name: "Autre pays", note: "Si ton pays n'est pas dans la procédure Études en France, France-Visas indique le circuit." },
];

export const levels = [
  { id: "bachelor", name: "Bachelor" },
  { id: "master", name: "Master" },
  { id: "doctorat", name: "Doctorat" },
  { id: "autre", name: "Autre formation" },
];

const idf = {
  transportName: "Île-de-France Mobilités",
  transportHref: "https://www.iledefrance-mobilites.fr/",
};
const sncf = {
  transportName: "SNCF Connect",
  transportHref: "https://www.sncf-connect.com/",
};

export const cities = [
  { id: "aix-en-provence", name: "Aix-en-Provence", ...sncf },
  { id: "ajaccio", name: "Ajaccio", ...sncf },
  { id: "amiens", name: "Amiens", ...sncf },
  { id: "angers", name: "Angers", transportName: "Irigo", transportHref: "https://www.irigo.fr/" },
  { id: "angouleme", name: "Angoulême", ...sncf },
  { id: "annecy", name: "Annecy", transportName: "Sibra", transportHref: "https://www.sibra.fr/" },
  { id: "antibes", name: "Antibes", ...sncf },
  { id: "argenteuil", name: "Argenteuil", ...idf },
  { id: "asnieres-sur-seine", name: "Asnières-sur-Seine", ...idf },
  { id: "aubervilliers", name: "Aubervilliers", ...idf },
  { id: "aulnay-sous-bois", name: "Aulnay-sous-Bois", ...idf },
  { id: "avignon", name: "Avignon", ...sncf },
  { id: "bastia", name: "Bastia", ...sncf },
  { id: "bayonne", name: "Bayonne", ...sncf },
  { id: "besancon", name: "Besançon", ...sncf },
  { id: "beziers", name: "Béziers", ...sncf },
  { id: "bordeaux", name: "Bordeaux", transportName: "TBM", transportHref: "https://www.infotbm.com/" },
  { id: "boulogne-billancourt", name: "Boulogne-Billancourt", ...idf },
  { id: "brest", name: "Brest", transportName: "Bibus", transportHref: "https://www.bibus.fr/" },
  { id: "caen", name: "Caen", transportName: "Twisto", transportHref: "https://www.twisto.fr/" },
  { id: "calais", name: "Calais", ...sncf },
  { id: "cannes", name: "Cannes", ...sncf },
  { id: "cayenne", name: "Cayenne", ...sncf },
  { id: "cergy", name: "Cergy", ...idf },
  { id: "chambery", name: "Chambéry", ...sncf },
  { id: "champigny-sur-marne", name: "Champigny-sur-Marne", ...idf },
  { id: "clermont-ferrand", name: "Clermont-Ferrand", transportName: "T2C", transportHref: "https://www.t2c.fr/" },
  { id: "clichy", name: "Clichy", ...idf },
  { id: "colmar", name: "Colmar", ...sncf },
  { id: "colombes", name: "Colombes", ...idf },
  { id: "courbevoie", name: "Courbevoie", ...idf },
  { id: "creteil", name: "Créteil", ...idf },
  { id: "dijon", name: "Dijon", transportName: "Divia", transportHref: "https://www.divia.fr/" },
  { id: "dunkerque", name: "Dunkerque", ...sncf },
  { id: "fort-de-france", name: "Fort-de-France", ...sncf },
  { id: "grenoble", name: "Grenoble", transportName: "TAG", transportHref: "https://www.tag.fr/" },
  { id: "issy-les-moulineaux", name: "Issy-les-Moulineaux", ...idf },
  { id: "ivry-sur-seine", name: "Ivry-sur-Seine", ...idf },
  { id: "le-havre", name: "Le Havre", ...sncf },
  { id: "le-mans", name: "Le Mans", ...sncf },
  { id: "levallois-perret", name: "Levallois-Perret", ...idf },
  { id: "lille", name: "Lille", transportName: "Ilévia", transportHref: "https://www.ilevia.fr/" },
  { id: "limoges", name: "Limoges", ...sncf },
  { id: "lorient", name: "Lorient", ...sncf },
  { id: "lyon", name: "Lyon", transportName: "TCL", transportHref: "https://www.tcl.fr/" },
  { id: "marseille", name: "Marseille", transportName: "RTM", transportHref: "https://www.rtm.fr/" },
  { id: "merignac", name: "Mérignac", transportName: "TBM", transportHref: "https://www.infotbm.com/" },
  { id: "metz", name: "Metz", ...sncf },
  { id: "montpellier", name: "Montpellier", transportName: "TaM", transportHref: "https://www.tam-voyages.com/" },
  { id: "montauban", name: "Montauban", ...sncf },
  { id: "montreuil", name: "Montreuil", ...idf },
  { id: "mulhouse", name: "Mulhouse", ...sncf },
  { id: "nancy", name: "Nancy", transportName: "STAN", transportHref: "https://www.reseau-stan.com/" },
  { id: "nanterre", name: "Nanterre", ...idf },
  { id: "nantes", name: "Nantes", transportName: "TAN", transportHref: "https://www.tan.fr/" },
  { id: "neuilly-sur-seine", name: "Neuilly-sur-Seine", ...idf },
  { id: "nice", name: "Nice", transportName: "Lignes d'Azur", transportHref: "https://www.lignesdazur.com/" },
  { id: "nimes", name: "Nîmes", ...sncf },
  { id: "niort", name: "Niort", ...sncf },
  { id: "noisy-le-grand", name: "Noisy-le-Grand", ...idf },
  { id: "orleans", name: "Orléans", ...sncf },
  { id: "paris", name: "Paris", ...idf },
  { id: "pau", name: "Pau", ...sncf },
  { id: "perpignan", name: "Perpignan", ...sncf },
  { id: "pessac", name: "Pessac", transportName: "TBM", transportHref: "https://www.infotbm.com/" },
  { id: "pointe-a-pitre", name: "Pointe-à-Pitre", ...sncf },
  { id: "poitiers", name: "Poitiers", ...sncf },
  { id: "quimper", name: "Quimper", ...sncf },
  { id: "reims", name: "Reims", ...sncf },
  { id: "rennes", name: "Rennes", transportName: "STAR", transportHref: "https://www.star.fr/" },
  { id: "rouen", name: "Rouen", transportName: "Astuce", transportHref: "https://www.reseau-astuce.fr/" },
  { id: "roubaix", name: "Roubaix", transportName: "Ilévia", transportHref: "https://www.ilevia.fr/" },
  { id: "rueil-malmaison", name: "Rueil-Malmaison", ...idf },
  { id: "saint-denis", name: "Saint-Denis", ...idf },
  { id: "saint-denis-reunion", name: "Saint-Denis (La Réunion)", ...sncf },
  { id: "saint-etienne", name: "Saint-Étienne", transportName: "STAS", transportHref: "https://www.reseau-stas.fr/" },
  { id: "saint-nazaire", name: "Saint-Nazaire", ...sncf },
  { id: "saint-paul", name: "Saint-Paul (La Réunion)", ...sncf },
  { id: "saint-maur-des-fosses", name: "Saint-Maur-des-Fossés", ...idf },
  { id: "strasbourg", name: "Strasbourg", transportName: "CTS", transportHref: "https://www.cts-strasbourg.eu/" },
  { id: "toulon", name: "Toulon", transportName: "Mistral", transportHref: "https://www.reseaumistral.com/" },
  { id: "toulouse", name: "Toulouse", transportName: "Tisséo", transportHref: "https://www.tisseo.fr/" },
  { id: "tourcoing", name: "Tourcoing", transportName: "Ilévia", transportHref: "https://www.ilevia.fr/" },
  { id: "tours", name: "Tours", transportName: "Fil Bleu", transportHref: "https://www.filbleu.fr/" },
  { id: "troyes", name: "Troyes", ...sncf },
  { id: "valence", name: "Valence", ...sncf },
  { id: "versailles", name: "Versailles", ...idf },
  { id: "villeurbanne", name: "Villeurbanne", transportName: "TCL", transportHref: "https://www.tcl.fr/" },
  { id: "villeneuve-dascq", name: "Villeneuve-d'Ascq", transportName: "Ilévia", transportHref: "https://www.ilevia.fr/" },
  { id: "vitry-sur-seine", name: "Vitry-sur-Seine", ...idf },
  { id: "autre", name: "Une autre ville", ...sncf },
];

export const needs: { id: Intent; title: string; text: string }[] = [
  { id: "preparer", title: "Je prépare mon arrivée", text: "Visa, documents, logement et budget avant le départ." },
  { id: "arrive", title: "Je viens d'arriver", text: "Les premières démarches après l'arrivée." },
  { id: "logement", title: "Je cherche un logement", text: "CROUS, garant, bail et aides." },
  { id: "emploi", title: "Je cherche un emploi étudiant", text: "Le droit de travailler, puis où chercher." },
  { id: "demarches", title: "Je veux comprendre les démarches", text: "Une explication, puis le site officiel." },
];

export const steps: Step[] = [
  {
    id: "documents",
    title: "Rassembler les documents",
    phase: "avant",
    intents: ["preparer", "demarches"],
    summary: "Passeport, admission et pièces demandées. Tu les gardes chez toi : Parcourstudent ne les stocke pas.",
    details: [
      "Vérifie la date du passeport avant le rendez-vous visa.",
      "La liste exacte est sur France-Visas.",
      "Aucun fichier n'est envoyé sur cette plateforme.",
    ],
    links: [
      { label: "France-Visas", href: "https://france-visas.gouv.fr/", publisher: "Ministère de l'Intérieur" },
      { label: "Campus France", href: "https://pastel.diplomatie.gouv.fr/etudesenfrance/dyn/public/authentification/login.html", publisher: "Campus France" },
    ],
  },
  {
    id: "visa",
    title: "Demander le visa étudiant",
    phase: "avant",
    intents: ["preparer", "demarches"],
    summary: "Hors Europe, il s'agit en général d'un visa long séjour mention étudiant. Ce n'est pas automatique.",
    details: [
      "France-Visas indique la procédure et le lieu de dépôt.",
      "Certains pays passent par Études en France, d'autres non.",
    ],
    links: [
      { label: "Visa ou titre de séjour étudiant", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F2231", publisher: "Service-Public" },
    ],
    caution: "Les règles peuvent différer selon la nationalité. Lis la fiche qui te concerne.",
  },
  {
    id: "cvec",
    title: "Obtenir l'attestation CVEC",
    phase: "avant",
    intents: ["preparer", "arrive", "demarches"],
    summary: "Beaucoup d'établissements demandent l'attestation avant l'inscription. Le paiement se fait sur le site officiel.",
    details: ["Le montant de l'année est affiché sur le site de la CVEC.", "Certaines situations sont exonérées."],
    links: [{ label: "CVEC", href: "https://cvec.etudiant.gouv.fr/", publisher: "Étudiant.gouv" }],
  },
  {
    id: "logement",
    title: "Chercher un logement",
    phase: "avant",
    intents: ["preparer", "logement"],
    summary: "Commence par le CROUS et le service logement de ton établissement.",
    details: [
      "Les dates de demande changent chaque année.",
      "Méfie-toi d'un virement demandé avant visite.",
    ],
    links: [
      { label: "Demander un logement CROUS", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F31912", publisher: "Service-Public" },
      { label: "Offres CROUS", href: "https://trouverunlogement.lescrous.fr/", publisher: "CROUS" },
    ],
  },
  {
    id: "visale",
    title: "Prévoir un garant",
    phase: "avant",
    intents: ["preparer", "logement"],
    summary: "Visale est une garantie publique, si tu remplis les conditions affichées sur leur site.",
    details: ["Fais la demande avant de signer le bail.", "Lis le contrat en entier."],
    links: [{ label: "Visale", href: "https://www.visale.fr/", publisher: "Action Logement" }],
  },
  {
    id: "valider-visa",
    title: "Valider le visa à l'arrivée",
    phase: "apres",
    intents: ["arrive", "demarches"],
    summary: "Un visa long séjour valant titre de séjour se valide en ligne. Le délai indiqué par l'administration est de trois mois.",
    details: ["La démarche se fait sur le portail des étrangers.", "Conserve la confirmation. Ne l'envoie pas ici."],
    links: [
      { label: "Valider un VLS-TS", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/R52684", publisher: "Service-Public" },
      { label: "Portail des étrangers", href: "https://administration-etrangers-en-france.interieur.gouv.fr/", publisher: "Ministère de l'Intérieur" },
    ],
    caution: "Sans validation dans le délai, le séjour peut devenir irrégulier.",
  },
  {
    id: "sante",
    title: "S'affilier à l'Assurance Maladie",
    phase: "apres",
    intents: ["arrive", "preparer", "demarches"],
    summary: "L'affiliation se demande sur le site dédié aux étudiants étrangers, avec l'inscription dans l'établissement.",
    details: ["Une assurance voyage ne remplace pas l'affiliation française.", "Les étudiants européens peuvent avoir une carte européenne."],
    links: [
      { label: "Démarche Ameli", href: "https://www.ameli.fr/assure/droits-demarches/europe-international/protection-sociale-france/vous-venez-etudier-en-france", publisher: "Ameli" },
      { label: "Inscription étudiant étranger", href: "https://etudiant-etranger.ameli.fr/", publisher: "Assurance Maladie" },
    ],
  },
  {
    id: "banque",
    title: "Ouvrir un compte bancaire",
    phase: "apres",
    intents: ["arrive", "logement"],
    summary: "Une banque peut refuser. Elle doit alors t'indiquer le droit au compte auprès de la Banque de France.",
    details: ["Pièce d'identité, justificatif de domicile et certificat de scolarité sont souvent demandés.", "Les pièces se présentent à la banque, pas sur Parcourstudent."],
    links: [
      { label: "Ouvrir un compte", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F2413", publisher: "Service-Public" },
      { label: "Droit au compte", href: "https://www.banque-france.fr/fr/a-votre-service/particuliers/droit-au-compte-bancaire", publisher: "Banque de France" },
    ],
  },
  {
    id: "transport",
    title: "Prendre les transports",
    phase: "apres",
    intents: ["arrive", "preparer"],
    summary: "L'abonnement étudiant se demande auprès du réseau de ta ville.",
    details: ["Le tarif change selon la ville et l'année.", "Pour les trajets entre villes, regarde la SNCF."],
    links: [{ label: "SNCF Connect", href: "https://www.sncf-connect.com/", publisher: "SNCF" }],
  },
  {
    id: "caf",
    title: "Vérifier l'aide au logement",
    phase: "apres",
    intents: ["arrive", "logement"],
    summary: "L'aide se demande à la CAF après le bail. Depuis juillet 2026, les conditions ont changé pour une partie des étudiants hors Union européenne.",
    details: ["Ne compte pas cette aide dans ton budget avant la décision de la CAF."],
    links: [
      { label: "CAF", href: "https://www.caf.fr/", publisher: "CAF" },
      { label: "Conditions d'APL", href: "https://www.service-public.gouv.fr/particuliers/actualites/A18981", publisher: "Service-Public" },
    ],
    caution: "Le dépôt d'un dossier n'ouvre pas le droit.",
  },
  {
    id: "emploi",
    title: "Vérifier le droit de travailler",
    phase: "apres",
    intents: ["emploi"],
    summary: "Avec un visa ou une carte étudiant, le travail salarié est limité. Service-Public indique 964 heures par an.",
    details: ["Au-delà, l'employeur doit obtenir une autorisation.", "La règle n'est pas identique pour toutes les nationalités."],
    links: [{ label: "Travail d'un étudiant non européen", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F2713", publisher: "Service-Public" }],
  },
  {
    id: "job",
    title: "Chercher un job étudiant",
    phase: "apres",
    intents: ["emploi"],
    summary: "Commence par les annonces du CROUS et de ton établissement.",
    details: ["Demande un contrat écrit.", "Les horaires doivent rester compatibles avec les cours."],
    links: [{ label: "Jobaviz", href: "https://www.jobaviz.fr/", publisher: "CROUS" }],
  },
];

export const guides = [
  { slug: "avant-arrivee", title: "Préparer l'arrivée", intro: "Ce qu'il est utile de régler avant l'avion.", intent: "preparer" as Intent },
  { slug: "apres-arrivee", title: "Les premiers jours", intro: "L'ordre des démarches après l'arrivée.", intent: "arrive" as Intent },
  { slug: "logement", title: "Chercher un logement", intro: "CROUS, garant, bail et aide éventuelle.", intent: "logement" as Intent },
  { slug: "emploi", title: "Emploi étudiant", intro: "D'abord le droit de travailler.", intent: "emploi" as Intent },
  { slug: "demarches", title: "Démarches administratives", intro: "Une explication, puis l'administration qui décide.", intent: "demarches" as Intent },
];

export const byId = <T extends { id: string }>(list: T[], id: string | undefined) =>
  list.find((item) => item.id === id);

export const stepsFor = (intent: Intent) => steps.filter((step) => step.intents.includes(intent));
